### ISSUE TITLE
Typo in exercises section

### ISSUE THREAD

**Issue by gnwx** [sumn2u/learn-javascript#19] opened 2023-07-03 14:14 UTC
Small typo missing "t":
"The Get the Tiles! problem"
https://github.com/sumn2u/learn-javascript/blob/main/en/exercises/get-the-titles.md

**Comment by sumn2u** [comment] 2023-07-03 16:25
Thanks for pointing the issue.  The issue is fixed in [this](https://github.com/sumn2u/learn-javascript/commit/fa2c2bc5d7e109e2f56f4a4ae84e025cda783867) commit.

**Closed by sumn2u** 2023-07-03 16:25 UTC
